[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
libs = ["node_modules"]
fs_permissions = [{ access = "read", path = "out-optimized" }]
allow_paths = ["*", "/"]
optimizer = true
optimizer_runs = 200
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.5.0" }

[rpc_endpoints]
default = "https://rpc-testnet.nerochain.io"
testnet = "https://rpc-testnet.nerochain.io"

[profile.networks]
testnet = { chain_id = 689, rpc_url = "https://rpc-testnet.nerochain.io" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options